### ISSUE TITLE
Error in .local(x, y, ...) : negative length vectors are not allowed (Memory Limits)

### ISSUE THREAD

**Issue by katPa90** [kollerma/robustlmm#14]
Hi! 
I hope this is the right place to ask this question.
I am relatively new to using linear models. For one specific question, my supervisor asked me to use rlmer (and this package) to test an effect. However, my dataset is relatively long (76 subjects à 770 trials). I model three fixed and one random effects. However, by using rlmer I reach the capacity limits of my processor, as I receive the error 

`Error in .local(x, y, ...) : negative length vectors are not allowed`

[I do not receive this error if I use only a subset of the subjects and trials.]

Is there a way to get this running on my machine? 

Best
Kat

**Comment by kollerma** [comment]
Dear Kat

Have you tried using `rlmerRcpp` instead of `rlmer`? 

`rlmerRcpp` uses an alternative implementation that does more in c++. That implementation might be slightly more memory efficient. Otherwise you're going to have to simplify your model or run it on a larger machine.

Best,
Manuel
