### ISSUE TITLE
Error in Ptr$initMatrices() : std::bad_alloc

### ISSUE THREAD

**Issue by abdullahicen** [kollerma/robustlmm#16]
Hi,
I'm trying to model in rlmer and my data set is long (20k data for 1500 earthquakes). First i tried to run rlmer and get this error

`Error in .local(x, y, ...) : 
  Cholmod error 'out of memory' at file ../Core/cholmod_memory.c, line 146`

and then when i saw the answer in the previous question i tried rlmerRcpp and got that error

`Error in Ptr$initMatrices() : std::bad_alloc`

Is there any way to solve this problem in my computer. Thank you for your interest.
Bests

**Comment by kollerma** [comment]
Hello

I'm assuming you have tried simpler model formulation and determined you need the model you're trying to fit. 

The easiest way is to run on another machine with more ram. If that is not an option, there are a few things you can try to maximise the free ram on your machine: 
- Make sure you're running R in 64 bit mode. 
- Close all other programs on your machine.
- Run just the R terminal, not RStudio. 
- Make sure your R environment is clean and only contains the data it really needs. 

Unfortunately the initialisation requires quite a bit of memory, more so than the fitting process itself. It's possible that the memory requirement can be reduced using some clever linear algebra. Given the right trick, it should be quite easy to change the code. 

Best, 
Manuel
