### ISSUE TITLE
Linking robustlmm to mice 

### ISSUE THREAD

**Issue by aanders8** [kollerma/robustlmm#17]
Greetings! Thanks for the great package. I don't know if this is a possibility, but is there any way robustlmm can be used on imputed data sets, particularly those made available via the mice package?

**Comment by kollerma** [comment]
Thanks for your interest. I'm sure it's technically possible to get robustlmm to work with the mice package. I won't have any capacity to implement something like this anytime soon.

I'm not sure that would work that well, though. You would have to deal with robustness issues in the imputation as well as the fitting - not sure how one would do that (on first thought).
