### ISSUE TITLE
Error in UseMethod("estfun") 

### ISSUE THREAD

**Issue by sneupane2** [kollerma/robustlmm#20]
I got this message when using sandwich:
Error in UseMethod("estfun") :
no applicable method for 'estfun' applied to an object of class "c('glmerMod', 'merMod')"

**Comment by sneupane2** [comment]
All I need is just the robust standard error, using glmer function (binomial, logit)

**Comment by kollerma** [comment]
Dear sneupane2

Not sure why your posting this here. The robustlmm package does not have any connection to neither glmer nor sandwich. Please ask in a more appropriate place such as https://stat.ethz.ch/mailman/listinfo/r-sig-mixed-models

Best,
Manuel
