### ISSUE TITLE
loading package crashes RStudio and forces session restart

### ISSUE THREAD

**Issue by jhaltiga** [kollerma/robustlmm#21]
Currently using latest versions of RStudio + R + robustlmm. Please advise.

**Comment by kollerma** [comment]
robustlmm depends on Rcpp. Installing them at different times may have lead to a binary incompatibility.

Reinstalling the Rcpp package and all packages that relate to it should solve your issue.

**Comment by jhaltiga** [comment]
> robustlmm depends on Rcpp. Installing them at different times may have lead to a binary incompatibility.
> 
> Reinstalling the Rcpp package and all packages that relate to it should solve your issue.

Thanks. This appears to have worked.
