### ISSUE TITLE
How to estimate p-value from rlmer object

### ISSUE THREAD

**Issue by AST87** [kollerma/robustlmm#22]
Hi Manuel,

   This might be a repetition but could you please suggest a way to estimate the p-value using the rlmer object? Additionally, from previously closed issues, I understood that Wald's test could be performed. Could you please suggest a package that could use rlmer object to perform Wald's test?

**Comment by kollerma** [comment]
Dear AST87,

There is no package that does this yet. Please have a look at https://github.com/masonFG/CIrobustLMM. You can find some scripts that compute confidence intervals and p-values in the best way currently know.

Best,
Manuel
