### ISSUE TITLE
Some difficulties in reading the Chapter 3 of Robust Estimation of Linear Mixed Models.

### ISSUE THREAD

**Issue by YuquanW** [kollerma/robustlmm#26]
Hi
I would be appreciatie if you could provide more details of these questions:
1. How to derive (3.12)/(3.14) from (3.10)/(3.11)? The $\hat\sigma$ is in (3.12)/(3.14) but not in (3.10)/(3.11).
2. In page 39, how does $Q_l(\theta)=U_b(\theta)^{-1}\frac{\partial U_b(\theta)}{\theta_l}$ reduce to ones and zeros in the case of diagonal $U_b(\theta)$?
3. Equation (3.11) to (3.14), why should $\hat{b}^{\ast}$ be scaled by $\hat{\sigma}$ instead of $\theta_l$?

Thank you.
Best regards.

**Comment by kollerma** [comment]
Hi

I'm assuming you're referring to equations in my dissertation,
Koller, M. (2013). Robust estimation of linear mixed models. Diss., ETH Zürich, Nr. 20997, 2013. https://doi.org/10.3929/ethz-a-007632241

1. $\hat\sigma$ is swallowed by the expectation. We recognize this to be a regular scale estimator, so we replace it by the formulas derived for the DAS-scale for linear regression.
2. I don't have my notes readily available. What matters is that for one $l$, there are no occurrences of $\theta_h$ where $h \neq l$. That means we can estimate each $\theta_l$ using a similar equation as for $\sigma$.
3. $\mathbf b^\ast$ is the spherical random effect, assumed to be $\mathbf{\mathcal{N}}(0, \sigma^2\mathbf I_q)$. The $\theta_l$ terms are only present in $\mathbf b$ after they have been introduced by $\mathbf U_b$, i.e., $\mathbf b = \mathbf U_b \mathbf b^*$.

Hope this helps.

Best,
Manuel

**Comment by YuquanW** [comment]
Thank you for your kind help. I forgot that $\theta_l$ was cancelled in both sides of (3.11).

Best regards,
Yuquan
