### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Hamedhm** [kollerma/robustlmm#6]
When I run the rlmer on my dataset I get:

Error in .local(x, y, ...) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_sparse.c, line 92

My dataset contains 48000 datapoints.

**Comment by kollerma** [comment]
rlmer uses quite a bit of memory in the initialisation. Unfortunately, there's not much that can be done about that. You'll have to try to run it on a machine with more memory.

**Comment by Hamedhm** [comment]
Thanks.
