### ISSUE TITLE
Error when new levels exist in data for prediction

### ISSUE THREAD

**Issue by Silverneo** [kollerma/robustlmm#8]
Hi Manuel, when I fit the model and try to predict with new data, I met the error saying that factor has new levels. the `allow.new.levels` option seems not working. Is this the expected behavior or I did something wrong? Thank you!

```
test_preds <- predict(fit, dat_all[SplitFlag==1,], allow.new.levels = TRUE)

Error in model.frame.default(delete.response(Terms), newdata, na.action = na.action,  : 
  factor X2 has new levels ab, ad, aj, ax, u, w
```

**Comment by kollerma** [comment]
Hi Silverneo, 
Sorry for the late answer. I'm not sure what the problem is. If I try it on my machine (using other data of course), everything works as expected. Could you please provide a minimal reproducible example? Thanks.

**Comment by Silverneo** [comment]
Hi Manuel, sorry for the later reply, I think I made a mistake that I included other factor columns which are not used for model training. Close the issue and sorry for the confusion.
